version: "3.7"
services:
  rabbitmq_api_service:
    build: .
    restart: always
    ports:
      - "9226:9225"
    depends_on:
      - spring_rabbitmq
    command: sh -c './wait-for spring_rabbitmq:5672 -- npm start'
  spring_rabbitmq:
    container_name: "spring_rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      # AMQP protocol port
      - "5674:5672"
      # HTTP management UI
      - "15674:15672"
volumes:
  rabbitmq_spring_boot:
